package basket.server.dao.database.app;

import basket.server.model.app.App;
import basket.server.util.IllegalActionException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.stereotype.Repository;

@Repository("localAppDAO")
public class LocalAppDAO implements AppDAO {

    private static final List<App> localDB = new ArrayList<>();

    @Override
    public Optional<App> getById(String id) {
        return localDB.stream()
                .filter(app -> app.getId().equals(id))
                .findFirst();
    }

    @Override
    public Optional<App> getByName(String name) {
        return localDB.stream()
                .filter(app -> app.getName().equals(name))
                .findFirst();
    }

    @Override
    public Collection<App> getAll() {
        return localDB;
    }

    @Override
    public Collection<App> get(Collection<String> names) {
        return localDB.stream()
                .filter(app -> names.contains(app.getName()))
                .toList();
    }

    @Override
    public void add(App newApp) throws IllegalActionException {
        // ID of new app is generated by the database
        newApp.setId(UUID.randomUUID().toString());

        if (isUnique(newApp)) {
            localDB.add(newApp);
        } else {
            throw new IllegalActionException("Some of the values are already taken");
        }
    }

    @Override
    public void update(App updatedApp) throws IllegalActionException {
        if (!validUpdate(updatedApp)) {
            throw new IllegalActionException("Could not find app to update or some of the new values are already taken");
        }

        for (int i = 0; i < localDB.size(); i++) {
            if (localDB.get(i).getId().equals(updatedApp.getId())) {
                localDB.set(i, updatedApp);
                return;
            }
        }
    }
}
